title:        'places by p1to'
description:  'A list of notable places'
url:          'http://places.p1to.kim'
email:        'me@p1to.kim'
permalink:    '/posts/:year-:month/:title'

markdown:     kramdown

naver:
  client:     'KYYYEDLbsazUa8bsKjck'

exclude:
  - Gemfile
  - Gemfile.lock
